version: '3'
services:
  api:
    image: tryretool/backend:latest
    env_file: ./docker.env
    depends_on:
      - postgres
    command: bash -c "./docker_scripts/wait-for-it.sh postgres:5432; ./docker_scripts/start_api.sh"
    ports:
      - 4000:3000

  postgres:
    image: postgres:9.6.5
    env_file: ./docker.env
    volumes:
      - ./.db/retool:/var/lib/postgresql/data
